name: CI
on: [push, pull_request]
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run JCJ tests with server
        run: npm run test-local-JCJ
